name: cardflip
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  no_glow_scroll: ^0.0.1
  percent_indicator: ^4.0.1
  auto_size_text: ^3.0.0
  go_router: ^3.1.1
  flip_card: ^0.5.0
  flutter_svg: ^1.1.6
  flare_flutter: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_riverpod: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "Images/logo/playstore.png"
  image_path_ios: "Images/logo/appstore.png"
  adaptive_icon_background: "Images/logo/icon_background.png"
  # adaptive_icon_foreground: "Images/logo/icon_transparent.png"
  remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Images/
    - Images/icons/svg/
    - Images/icons/
    - Images/backgrounds/
    - Images/cards/flashcards/
    - Images/cards/homepage/1_3/0/
    - Images/cards/homepage/1_3/1/
    - Images/cards/homepage/1_3/2/
    - Images/cards/homepage/1_3/3/
    - Images/cards/homepage/1_3/4/
    - Images/cards/homepage/1_3/5/
    - Images/cards/homepage/1_3/6/
    - Images/cards/homepage/1_3/7/
    - Images/cards/homepage/1_3/8/
    - Images/cards/homepage/1_3/9/
    - Images/cards/homepage/1_3/10/
    - Images/cards/homepage/1_3/11/
    - Images/cards/homepage/1_3/12/
    - Images/cards/homepage/1_3/13/
    - Images/cards/homepage/1_3/14/
    - Images/cards/homepage/1_3/15/
    - Images/cards/categorypage/1/0/
    - Images/cards/categorypage/1/1/
    - Images/cards/categorypage/1/2/
    - Images/cards/categorypage/1/3/
    - Images/cards/categorypage/1/4/
    - Images/cards/categorypage/1/5/
    - Images/cards/categorypage/1/6/
    - Images/cards/categorypage/1/7/
    - Images/cards/categorypage/1/8/
    - Images/cards/categorypage/1/9/
    - Images/cards/categorypage/1/10/
    - Images/cards/categorypage/1/11/
    - Images/cards/categorypage/1/12/
    - Images/cards/categorypage/1/13/
    - Images/cards/categorypage/1/14/
    - Images/cards/categorypage/1/15/
    - Images/cards/categorypage/2/0/
    - Images/cards/categorypage/2/1/
    - Images/cards/categorypage/2/2/
    - Images/cards/categorypage/2/3/
    - Images/cards/categorypage/2/4/
    - Images/cards/categorypage/2/5/
    - Images/cards/categorypage/2/6/
    - Images/cards/categorypage/2/7/
    - Images/cards/categorypage/2/8/
    - Images/cards/categorypage/2/9/
    - Images/cards/categorypage/2/10/
    - Images/cards/categorypage/2/11/
    - Images/cards/categorypage/2/12/
    - Images/cards/categorypage/2/13/
    - Images/cards/categorypage/2/14/
    - Images/cards/categorypage/2/15/
    - Images/cards/categorypage/3_1/0/
    - Images/cards/categorypage/3_1/1/
    - Images/cards/categorypage/3_1/2/
    - Images/cards/categorypage/3_1/3/
    - Images/cards/categorypage/3_1/4/
    - Images/cards/categorypage/3_1/5/
    - Images/cards/categorypage/3_1/6/
    - Images/cards/categorypage/3_1/7/
    - Images/cards/categorypage/3_1/8/
    - Images/cards/categorypage/3_1/9/
    - Images/cards/categorypage/3_1/10/
    - Images/cards/categorypage/3_1/11/
    - Images/cards/categorypage/3_1/12/
    - Images/cards/categorypage/3_1/13/
    - Images/cards/categorypage/3_1/14/
    - Images/cards/categorypage/3_1/15/
    - Images/cards/categorypage/3_2/0/
    - Images/cards/categorypage/3_2/1/
    - Images/cards/categorypage/3_2/2/
    - Images/cards/categorypage/3_2/3/
    - Images/cards/categorypage/3_2/4/
    - Images/cards/categorypage/3_2/5/
    - Images/cards/categorypage/3_2/6/
    - Images/cards/categorypage/3_2/7/
    - Images/cards/categorypage/3_2/8/
    - Images/cards/categorypage/3_2/9/
    - Images/cards/categorypage/3_2/10/
    - Images/cards/categorypage/3_2/11/
    - Images/cards/categorypage/3_2/12/
    - Images/cards/categorypage/3_2/13/
    - Images/cards/categorypage/3_2/14/
    - Images/cards/categorypage/3_2/15/
    - Images/cards/homepage/2/2_1/0/
    - Images/cards/homepage/2/2_1/1/
    - Images/cards/homepage/2/2_1/2/
    - Images/cards/homepage/2/2_1/3/
    - Images/cards/homepage/2/2_1/4/
    - Images/cards/homepage/2/2_1/5/
    - Images/cards/homepage/2/2_1/6/
    - Images/cards/homepage/2/2_1/7/
    - Images/cards/homepage/2/2_1/8/
    - Images/cards/homepage/2/2_1/9/
    - Images/cards/homepage/2/2_1/10/
    - Images/cards/homepage/2/2_1/11/
    - Images/cards/homepage/2/2_1/12/
    - Images/cards/homepage/2/2_1/13/
    - Images/cards/homepage/2/2_1/14/
    - Images/cards/homepage/2/2_1/15/
    - Images/cards/homepage/2/2_2/0/
    - Images/cards/homepage/2/2_2/1/
    - Images/cards/homepage/2/2_2/2/
    - Images/cards/homepage/2/2_2/3/
    - Images/cards/homepage/2/2_2/4/
    - Images/cards/homepage/2/2_2/5/
    - Images/cards/homepage/2/2_2/6/
    - Images/cards/homepage/2/2_2/7/
    - Images/cards/homepage/2/2_2/8/
    - Images/cards/homepage/2/2_2/9/
    - Images/cards/homepage/2/2_2/10/
    - Images/cards/homepage/2/2_2/11/
    - Images/cards/homepage/2/2_2/12/
    - Images/cards/homepage/2/2_2/13/
    - Images/cards/homepage/2/2_2/14/
    - Images/cards/homepage/2/2_2/15/
    - Images/cards/homepage/2/2_4/0/
    - Images/cards/homepage/2/2_4/1/
    - Images/cards/homepage/2/2_4/2/
    - Images/cards/homepage/2/2_4/3/
    - Images/cards/homepage/2/2_4/4/
    - Images/cards/homepage/2/2_4/5/
    - Images/cards/homepage/2/2_4/6/
    - Images/cards/homepage/2/2_4/7/
    - Images/cards/homepage/2/2_4/8/
    - Images/cards/homepage/2/2_4/9/
    - Images/cards/homepage/2/2_4/10/
    - Images/cards/homepage/2/2_4/11/
    - Images/cards/homepage/2/2_4/12/
    - Images/cards/homepage/2/2_4/13/
    - Images/cards/homepage/2/2_4/14/
    - Images/cards/homepage/2/2_4/15/
    - Images/cards/homepage/2/2_5/0/
    - Images/cards/homepage/2/2_5/1/
    - Images/cards/homepage/2/2_5/2/
    - Images/cards/homepage/2/2_5/3/
    - Images/cards/homepage/2/2_5/4/
    - Images/cards/homepage/2/2_5/5/
    - Images/cards/homepage/2/2_5/6/
    - Images/cards/homepage/2/2_5/7/
    - Images/cards/homepage/2/2_5/8/
    - Images/cards/homepage/2/2_5/9/
    - Images/cards/homepage/2/2_5/10/
    - Images/cards/homepage/2/2_5/11/
    - Images/cards/homepage/2/2_5/12/
    - Images/cards/homepage/2/2_5/13/
    - Images/cards/homepage/2/2_5/14/
    - Images/cards/homepage/2/2_5/15/
    - Images/cards/homepage/2/2_3/0/
    - Images/cards/homepage/2/2_3/1/
    - Images/cards/homepage/2/2_3/2/
    - Images/cards/homepage/2/2_3/3/
    - Images/cards/homepage/2/2_3/4/
    - Images/cards/homepage/2/2_3/5/
    - Images/cards/homepage/2/2_3/6/
    - Images/cards/homepage/2/2_3/7/
    - Images/cards/homepage/2/2_3/8/
    - Images/cards/homepage/2/2_3/9/
    - Images/cards/homepage/2/2_3/10/
    - Images/cards/homepage/2/2_3/11/
    - Images/cards/homepage/2/2_3/12/
    - Images/cards/homepage/2/2_3/13/
    - Images/cards/homepage/2/2_3/14/
    - Images/cards/homepage/2/2_3/15/
    - Images/cards/librarypage/0/
    - Images/cards/librarypage/1/
    - Images/cards/librarypage/2/
    - Images/cards/librarypage/3/
    - Images/cards/librarypage/4/
    - Images/cards/librarypage/5/
    - Images/cards/librarypage/6/
    - Images/cards/librarypage/7/
    - Images/cards/librarypage/8/
    - Images/cards/librarypage/9/
    - Images/cards/librarypage/10/
    - Images/cards/librarypage/11/
    - Images/cards/librarypage/12/
    - Images/cards/librarypage/13/
    - Images/cards/librarypage/14/
    - Images/cards/librarypage/15/
    - Images/banners/profilepage/
    - Images/banners/deckpage/
    - Images/banners/librarypage/
    - Images/banners/adddeck/
    - Images/avatars/
    - Images/vectors/
    - Images/banners/leaderboardpage/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PolySans_Slim
      fonts:
        - asset: fonts/PolySans_Slim.ttf
    - family: PolySans_Bulky_Wide
      fonts:
        - asset: fonts/PolySans_Bulky_Wide.otf
    - family: PolySans_Median
      fonts:
        - asset: fonts/PolySans_Median.ttf
    - family: PolySans_Neutral
      fonts:
        - asset: fonts/PolySans_Neutral.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
